name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Setup PNPM
        id: setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install Dependencies
        id: install
        run: pnpm install --frozen-lockfile

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          LINTER_RULES_PATH: ${{ github.workspace }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_JSON: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_JAVASCRIPT_PRETTIER	: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_SHELL_SHFMT: false
          FIX_JAVASCRIPT_PRETTIER: false
          FIX_JSON_PRETTIER: false
          FIX_SHELL_SHFMT: false
          FIX_YAML_PRETTIER: false
